# Generated by Django 6.0.7 on 2026-07-25 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_product_best_seller_product_discount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category_type',
            field=models.CharField(default='general', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='skin_concern',
            field=models.CharField(default='general', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='skin_type',
            field=models.CharField(default='general', max_length=50),
            preserve_default=False,
        ),
    ]
